//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDIntecap
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TblUsuarios
    {
        public int Usuario_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int NoTelefono { get; set; }
        public string Direccion { get; set; }
        public string CorreoElectronico { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool Activo { get; set; }
        public byte IdRol { get; set; }
        public string Contraseña { get; set; }
        [Required(ErrorMessage = "Rquerido")]
        [Compare("Contraseña", ErrorMessage = "Clave incorrecta")]
        public string ConfirmPassword { get; set; }
            
        public virtual TblRoles TblRoles { get; set; }
    }
}
